# hyprlang noerror false
# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

monitor=eDP-1,2880x1800@90.00Hz,auto,1.33


general{
    gaps_in = 2,
    gaps_out = 2
    }

# HDMI port: mirror display. To see device name, use `hyprctl monitors`
